; --- Global Project Configuration ---
[platformio]
default_envs = esp32dev
description = Basic ESP32 firmware for telemetry upload and LED control

[env]
check_tool = cppcheck

; --- Development Environment ---
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include
    -std=gnu++17

lib_deps =
    adafruit/DHT sensor library@^1.4.2
    adafruit/Adafruit Unified Sensor@^1.1.4
    teckel12/NewPing@^1.9.3
    bblanchon/ArduinoJson@^6.21.3

check_skip_packages = yes
test_build_src = false

test_filter = test_hardware_sensors/*

[env:esp32_simulation]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/DHT sensor library@^1.4.2
    adafruit/Adafruit Unified Sensor@^1.1.4
    teckel12/NewPing@^1.9.3
    bblanchon/ArduinoJson@^6.21.3
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include
    -std=gnu++17
    -D USE_MOCK_SENSORS
test_build_src = false
test_filter = test_hardware_sensors/*


[env:native_test]
platform = native
test_framework = googletest
lib_deps =
    fabiobatsilva/ArduinoFake@^0.4.0
lib_ignore =
    Network
build_flags =
    -std=gnu++17
    -I include
test_build_src = false
test_filter = test_mock_sensor_model
