name: Main Actions

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  frontend-building:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Frontend Building
        uses: ./.github/frontend/building

  frontend-testing:
    runs-on: ubuntu-latest

    needs:
      - frontend-building

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Frontend Testing
        uses: ./.github/frontend/testing