name: Main Actions

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main
      - development

jobs:

  frontend-build:
    name: Frontend Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Frontend Build
        uses: ./.github/frontend/building

  frontend-test:
    name: Frontend Tests

    runs-on: ubuntu-latest

    needs:
      - frontend-build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Frontend Tests
        uses: ./.github/frontend/test